build:
	docker-compose -p backend-template -f docker-compose.yml build --no-cache

up:
	docker-compose -p backend-template -f docker-compose.yml up

down:
	docker-compose -p backend-template -f docker-compose.yml down -v

pytest-run:
	pytest -s