/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Access Token
         * @description Эндпоинт для обновления access токена(который нужен для доступа к API)
         */
        post: operations["refresh_access_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description Регистрация аккаунта пользователя
         */
        post: operations["register_user_api_v1_auth_register_user_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login User
         * @description Вход в аккаунт пользователя
         */
        post: operations["login_user_api_v1_auth_login_user_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/check_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check User
         * @description Проверка пользователя на авторизацию
         */
        get: operations["check_user_api_v1_auth_check_user_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Logout
         * @description Проверка пользователя на авторизацию
         */
        get: operations["logout_api_v1_auth_logout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/get_user_by_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get User
         * @description Получение юзера по refresh токену
         */
        post: operations["get_user_api_v1_users_get_user_by_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/update_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Обновление данных пользователя
         */
        patch: operations["update_user_api_v1_users_update_user_patch"];
        trace?: never;
    };
    "/api/v1/rooms/get_rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rooms
         * @description Получение всех комнат доступных пользователю
         */
        get: operations["get_rooms_api_v1_rooms_get_rooms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/get_room_by_id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Room By Id
         * @description Получение комнаты по ID
         */
        post: operations["get_room_by_id_api_v1_rooms_get_room_by_id_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/create_room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Room
         * @description Создание комнаты, тот кто создал получает роль owner, то-есть создатель со своими правами, а при присоединении другого пользователя к комнате, пользователь получается роль member
         */
        post: operations["create_room_api_v1_rooms_create_room_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/update_room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Room
         * @description Обновление комнаты, позволяет выполнять любые обновления с комнатой
         */
        patch: operations["update_room_api_v1_rooms_update_room_patch"];
        trace?: never;
    };
    "/api/v1/rooms/invite_to_room_from_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite To Room From User
         * @description Приглашения в комнату ОТ пользователя через код комнаты
         */
        post: operations["invite_to_room_from_user_api_v1_rooms_invite_to_room_from_user_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/invite_from_room_to_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite From Room To User
         * @description Приглашения ИЗ комнаты через код пользователя
         */
        post: operations["invite_from_room_to_user_api_v1_rooms_invite_from_room_to_user_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/delete_member_from_room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Member From Room */
        post: operations["delete_member_from_room_api_v1_rooms_delete_member_from_room_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/delete_room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Room By Id */
        post: operations["delete_room_by_id_api_v1_rooms_delete_room_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/add_message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Message
         * @description Добавление сообщения в комнату
         */
        post: operations["add_message_api_v1_messages_add_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/update_message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Message
         * @description Обновление сообщения по ID в комнате
         */
        patch: operations["update_message_api_v1_messages_update_message_patch"];
        trace?: never;
    };
    "/api/v1/notifications/get_notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Notifications
         * @description Получение всех уведомлений пользователя
         */
        post: operations["get_notifications_api_v1_notifications_get_notifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/add_notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Notifications
         * @description Добавить уведомление
         */
        post: operations["add_notifications_api_v1_notifications_add_notification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/update_notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Notification
         * @description В основном для обновления is_read оповещения, и для принятие или отмены инвайтов
         */
        post: operations["update_notification_api_v1_notifications_update_notification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept_invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Invite
         * @description Принятие или отмена приглашения в комнату либо от пользователя либо от владельца комнаты
         */
        post: operations["accept_invite_api_v1_invitations_accept_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_invite_from_room_to_user_api_v1_rooms_invite_from_room_to_user_post */
        Body_invite_from_room_to_user_api_v1_rooms_invite_from_room_to_user_post: {
            invite_data: components["schemas"]["InviteCreate"];
            notification_data: components["schemas"]["NotificationCreate"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InviteCreate */
        InviteCreate: {
            /** Type */
            type: string;
        };
        /** InviteResponse */
        InviteResponse: {
            /** Id */
            id: string;
            /** Inviter Id */
            inviter_id: string;
            /** User Id */
            user_id: string;
            /** Room Id */
            room_id: string;
            /** Status */
            status: string;
            /** Type */
            type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MemberResponse */
        MemberResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            user: components["schemas"]["User"];
            /** Room Id */
            room_id: string;
            /** Role */
            role: string;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /** MessageCreate */
        MessageCreate: {
            /** Content */
            content: string;
            /** Room Id */
            room_id: string;
            /** User Id */
            user_id: string;
            /** Member Id */
            member_id: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Id */
            id: string;
            /** Content */
            content: string;
            /** Room Id */
            room_id: string;
            /** User Id */
            user_id: string;
            /** Member Id */
            member_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Read */
            is_read: boolean;
            user: components["schemas"]["UserResponse"];
        };
        /** MessageUpdate */
        MessageUpdate: {
            /** Content */
            content: string;
        };
        /** NotificationCreate */
        NotificationCreate: {
            /** Title */
            title: string;
        };
        /** NotificationResponse */
        NotificationResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Invite Id */
            invite_id: string;
            /** Title */
            title: string;
            /** Is Read */
            is_read: boolean;
            /** Type */
            type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NotificationUpdate */
        NotificationUpdate: {
            /** Title */
            title: string;
            /** Is Read */
            is_read: boolean;
        };
        /** RoomCreate */
        RoomCreate: {
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** RoomResponse */
        RoomResponse: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Id */
            id: string;
            /** Room Code */
            room_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Members
             * @default []
             */
            members: components["schemas"]["MemberResponse"][];
        };
        /** RoomResponseWithMessages */
        RoomResponseWithMessages: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Id */
            id: string;
            /** Room Code */
            room_code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Members
             * @default []
             */
            members: components["schemas"]["MemberResponse"][];
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["MessageResponse"][];
        };
        /** RoomUpdate */
        RoomUpdate: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Members */
            members: components["schemas"]["MemberResponse"][];
        };
        /** SuccessResponse[InviteResponse] */
        SuccessResponse_InviteResponse_: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["InviteResponse"] | null;
        };
        /** SuccessResponse[List[MessageResponse]] */
        SuccessResponse_List_MessageResponse__: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /** Message */
            message?: string | null;
            /** Data */
            data?: components["schemas"]["MessageResponse"][] | null;
        };
        /** SuccessResponse[List[NotificationResponse]] */
        SuccessResponse_List_NotificationResponse__: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /** Message */
            message?: string | null;
            /** Data */
            data?: components["schemas"]["NotificationResponse"][] | null;
        };
        /** SuccessResponse[List[RoomResponse]] */
        SuccessResponse_List_RoomResponse__: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /** Message */
            message?: string | null;
            /** Data */
            data?: components["schemas"]["RoomResponse"][] | null;
        };
        /** SuccessResponse[MessageResponse] */
        SuccessResponse_MessageResponse_: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["MessageResponse"] | null;
        };
        /** SuccessResponse[NoneType] */
        SuccessResponse_NoneType_: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /** Message */
            message?: string | null;
            /** Data */
            data?: null;
        };
        /** SuccessResponse[NotificationResponse] */
        SuccessResponse_NotificationResponse_: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["NotificationResponse"] | null;
        };
        /** SuccessResponse[RoomResponseWithMessages] */
        SuccessResponse_RoomResponseWithMessages_: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["RoomResponseWithMessages"] | null;
        };
        /** SuccessResponse[RoomResponse] */
        SuccessResponse_RoomResponse_: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["RoomResponse"] | null;
        };
        /** SuccessResponse[UserResponse] */
        SuccessResponse_UserResponse_: {
            /**
             * Status
             * @default 200
             */
            status: number;
            /** Message */
            message?: string | null;
            data?: components["schemas"]["UserResponse"] | null;
        };
        /** User */
        User: {
            /** Login */
            login: string;
            /** Email */
            email: string;
            /** Picture */
            picture: string | null;
        };
        /** UserCreate */
        UserCreate: {
            /** Login */
            login: string;
            /** Password */
            password: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** UserLogin */
        UserLogin: {
            /** Login */
            login: string;
            /** Password */
            password: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Login */
            login: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** User Code */
            user_code: string;
            /** Picture */
            picture: string | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Login */
            login: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** New Password */
            new_password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    refresh_access_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_user_api_v1_auth_register_user_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_UserResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_user_api_v1_auth_login_user_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_UserResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_user_api_v1_auth_check_user_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_UserResponse_"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_UserResponse_"];
                };
            };
        };
    };
    get_user_api_v1_users_get_user_by_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_UserResponse_"];
                };
            };
        };
    };
    update_user_api_v1_users_update_user_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_UserResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rooms_api_v1_rooms_get_rooms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_List_RoomResponse__"];
                };
            };
        };
    };
    get_room_by_id_api_v1_rooms_get_room_by_id_post: {
        parameters: {
            query: {
                room_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_RoomResponseWithMessages_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_room_api_v1_rooms_create_room_post: {
        parameters: {
            query: {
                user_id: string;
                role: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_RoomResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_room_api_v1_rooms_update_room_patch: {
        parameters: {
            query: {
                room_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_RoomResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_to_room_from_user_api_v1_rooms_invite_to_room_from_user_post: {
        parameters: {
            query: {
                user_code: string;
                room_code: string;
                title: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_InviteResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_from_room_to_user_api_v1_rooms_invite_from_room_to_user_post: {
        parameters: {
            query: {
                room_code: string;
                inviter_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_invite_from_room_to_user_api_v1_rooms_invite_from_room_to_user_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_InviteResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_member_from_room_api_v1_rooms_delete_member_from_room_post: {
        parameters: {
            query: {
                room_id: string;
                user_id: string;
                member_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_RoomResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_room_by_id_api_v1_rooms_delete_room_post: {
        parameters: {
            query: {
                room_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_RoomResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_message_api_v1_messages_add_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_MessageResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_message_api_v1_messages_update_message_patch: {
        parameters: {
            query: {
                message_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_List_MessageResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notifications_api_v1_notifications_get_notifications_post: {
        parameters: {
            query: {
                user_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_List_NotificationResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_notifications_api_v1_notifications_add_notification_post: {
        parameters: {
            query: {
                user_id: string;
                invite_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_NotificationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_notification_api_v1_notifications_update_notification_post: {
        parameters: {
            query: {
                user_id: string;
                notification_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_NotificationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invite_api_v1_invitations_accept_invite_post: {
        parameters: {
            query: {
                invite_id: string;
                notification_id: string;
                user_id: string;
                status: string;
                invite_type: "invite_from_room" | "invite_to_room";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
