/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Accordion: typeof import('./components/ui/accordion').Accordion
  const AccordionContent: typeof import('./components/ui/accordion').AccordionContent
  const AccordionItem: typeof import('./components/ui/accordion').AccordionItem
  const AccordionTrigger: typeof import('./components/ui/accordion').AccordionTrigger
  const Button: typeof import('./components/ui/button').Button
  const ChatStore: typeof import('./store/chat.store').ChatStore
  const Counter: typeof import('./components/Counter').Counter
  const DemoStore: typeof import('./store/demo.store').DemoStore
  const Dialog: typeof import('./components/ui/dialog').Dialog
  const DialogClose: typeof import('./components/ui/dialog').DialogClose
  const DialogContent: typeof import('./components/ui/dialog').DialogContent
  const DialogDescription: typeof import('./components/ui/dialog').DialogDescription
  const DialogFooter: typeof import('./components/ui/dialog').DialogFooter
  const DialogHeader: typeof import('./components/ui/dialog').DialogHeader
  const DialogOverlay: typeof import('./components/ui/dialog').DialogOverlay
  const DialogPortal: typeof import('./components/ui/dialog').DialogPortal
  const DialogTitle: typeof import('./components/ui/dialog').DialogTitle
  const DialogTrigger: typeof import('./components/ui/dialog').DialogTrigger
  const Drawer: typeof import('./components/ui/drawer').Drawer
  const DrawerClose: typeof import('./components/ui/drawer').DrawerClose
  const DrawerContent: typeof import('./components/ui/drawer').DrawerContent
  const DrawerDescription: typeof import('./components/ui/drawer').DrawerDescription
  const DrawerFooter: typeof import('./components/ui/drawer').DrawerFooter
  const DrawerHeader: typeof import('./components/ui/drawer').DrawerHeader
  const DrawerOverlay: typeof import('./components/ui/drawer').DrawerOverlay
  const DrawerPortal: typeof import('./components/ui/drawer').DrawerPortal
  const DrawerTitle: typeof import('./components/ui/drawer').DrawerTitle
  const DrawerTrigger: typeof import('./components/ui/drawer').DrawerTrigger
  const DropdownMenu: typeof import('./components/ui/dropdown-menu').DropdownMenu
  const DropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu').DropdownMenuCheckboxItem
  const DropdownMenuContent: typeof import('./components/ui/dropdown-menu').DropdownMenuContent
  const DropdownMenuGroup: typeof import('./components/ui/dropdown-menu').DropdownMenuGroup
  const DropdownMenuItem: typeof import('./components/ui/dropdown-menu').DropdownMenuItem
  const DropdownMenuLabel: typeof import('./components/ui/dropdown-menu').DropdownMenuLabel
  const DropdownMenuPortal: typeof import('./components/ui/dropdown-menu').DropdownMenuPortal
  const DropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu').DropdownMenuRadioGroup
  const DropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu').DropdownMenuRadioItem
  const DropdownMenuSeparator: typeof import('./components/ui/dropdown-menu').DropdownMenuSeparator
  const DropdownMenuShortcut: typeof import('./components/ui/dropdown-menu').DropdownMenuShortcut
  const DropdownMenuSub: typeof import('./components/ui/dropdown-menu').DropdownMenuSub
  const DropdownMenuSubContent: typeof import('./components/ui/dropdown-menu').DropdownMenuSubContent
  const DropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu').DropdownMenuSubTrigger
  const DropdownMenuTrigger: typeof import('./components/ui/dropdown-menu').DropdownMenuTrigger
  const EChatStore: typeof import('./store/chat.store').EChatStore
  const Example: typeof import('./components/VirtualList').Example
  const FullScreenLoader: typeof import('./components/FullScreenLoader').default
  const Header: typeof import('./components/Header').default
  const Loader: typeof import('./components/FullScreenLoader').default
  const Menu: typeof import('./components/Menu').default
  const MobileMenu: typeof import('./components/MobileMenu').default
  const RoomStore: typeof import('./store/demo.store').RoomStore
  const Select: typeof import('./components/ui/select').Select
  const SelectContent: typeof import('./components/ui/select').SelectContent
  const SelectGroup: typeof import('./components/ui/select').SelectGroup
  const SelectItem: typeof import('./components/ui/select').SelectItem
  const SelectLabel: typeof import('./components/ui/select').SelectLabel
  const SelectScrollDownButton: typeof import('./components/ui/select').SelectScrollDownButton
  const SelectScrollUpButton: typeof import('./components/ui/select').SelectScrollUpButton
  const SelectSeparator: typeof import('./components/ui/select').SelectSeparator
  const SelectTrigger: typeof import('./components/ui/select').SelectTrigger
  const SelectValue: typeof import('./components/ui/select').SelectValue
  const Sidebar: typeof import('./components/Sidebar').default
  const SocialButton: typeof import('./components/SocialButton').default
  const Table: typeof import('./components/ui/table').Table
  const TableBody: typeof import('./components/ui/table').TableBody
  const TableCaption: typeof import('./components/ui/table').TableCaption
  const TableCell: typeof import('./components/ui/table').TableCell
  const TableFooter: typeof import('./components/ui/table').TableFooter
  const TableHead: typeof import('./components/ui/table').TableHead
  const TableHeader: typeof import('./components/ui/table').TableHeader
  const TableRow: typeof import('./components/ui/table').TableRow
  const Test: typeof import('./components/Test').default
  const Toaster: typeof import('./components/ui/sonner').Toaster
  const VirtualList: typeof import('./components/VirtualList').default
  const axios: typeof import('axios').default
  const buttonVariants: typeof import('./components/ui/button').buttonVariants
  const counterStore: typeof import('./store/init.store').counterStore
  const createRef: typeof import('react').createRef
  const forwardRef: typeof import('react').forwardRef
  const initStore: typeof import('./store/init.store').default
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const togglerStore: typeof import('./store/toggler.store').togglerStore
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebounce: typeof import('./hooks/useDebounce').default
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useGetLinks: typeof import('./hooks/useGetLinks').default
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useMobile: typeof import('./hooks/useMobile').default
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const zustand: typeof import('zustand').create
}
// for type re-export
declare global {
  // @ts-ignore
  export type { EChatStore, ChatStore, TChatStore } from './store/chat.store'
  import('./store/chat.store')
}
