"""update user

Revision ID: 03d1623b0de7
Revises: 1cad6c51e8a1
Create Date: 2026-04-30 13:34:45.877896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d1623b0de7'
down_revision: Union[str, Sequence[str], None] = '1cad6c51e8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_room_messages_order', 'messages', ['room_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_messages_order', table_name='messages')
    # ### end Alembic commands ###
