"""update

Revision ID: 9cfdaf2f79e8
Revises: d1d91d0d334a
Create Date: 2026-05-18 14:09:32.104722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfdaf2f79e8'
down_revision: Union[str, Sequence[str], None] = 'd1d91d0d334a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('invite_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('notifications_invitation_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'invitations', ['invite_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'invitation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('invitation_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_invitation_id_fkey'), 'notifications', 'invitations', ['invitation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'invite_id')
    # ### end Alembic commands ###
